### ISSUE TITLE
Consider moving the README contents to a ReadTheDocs site.

### ISSUE THREAD

**Issue by jbonacci** [mozilla/fxa-deployment#34]
Something like
https://FxADeployment.readthedocs.org/en/latest/
and/or
https://FxALoadTesting.readthedocs.org/en/latest/

Great examples:
https://hekad.readthedocs.org/en/latest/
https://loads.readthedocs.org/en/latest/

Extra Credit:
Besides the README info and deployment info
1. add more stack info: processes, logs, etc
2. add load testing info
3. add info on how to use/configure Kibana dashboard

**Comment by vladikoff** [comment]
> NOTE: this repository is on longer in active use.
FxA deployment details are now part of the mozilla-services puppet-config repo.
